### ISSUE TITLE
Does not work on a Mockito PR

### ISSUE THREAD

**Issue by TimvdLippe** [dominique-mueller/web-extension-github-travis-status#14]
First of all: thank you for creating this extension! Sadly I couldn't make it work just yet, so would like to help out and debug what the issue is. On https://github.com/mockito/mockito/pull/1373 I expected to see our wide array of jobs (https://travis-ci.org/mockito/mockito/builds/367318861 shows the full matrix). However, I do not see any sub-job, only the overall one.

Do you maybe know why it is not working?

**Comment by itsdevdom** [comment]
Ah yes, at the moment the extension only works with the new Build Stages feature (see https://docs.travis-ci.com/user/build-stages/). Migrating should be fairly simple, I have done it for my repositories already.

**Comment by TimvdLippe** [comment]
Hm, maybe next to stages, taking the normal jobs would work as well? E.g. if stages are there, use them. Else resort back to the normal jobs of the build.

**Comment by itsdevdom** [comment]
Let me take a look at it :)

**Comment by itsdevdom** [comment]
I'll publish an update to the Chrome Web Store in a few minutes :)

**Comment by TimvdLippe** [comment]
Awesome, thanks for the quick turnaround!

Op di 1 mei 2018 om 16:55 schreef Dominique Müller <notifications@github.com

**Comment by itsdevdom** [comment]
Ok, I've uploaded and published the update successfully - yet it's still now showing up in the Chrome Web Store. Probably takes a few more minutes / hours, once it's finally here and you got the update let me know if everything works as expected :)

**Comment by TimvdLippe** [comment]
![image](https://user-images.githubusercontent.com/5948271/39479543-e0ac4144-4d65-11e8-9989-ddcfdaeca93c.png)
Yes it is working :smile: Maybe the name could be a little bit nicer, but this is a nice step anyways!

**Comment by itsdevdom** [comment]
Yeah, the build number basically is the name. There is, however, an open issue (https://github.com/travis-ci/travis-ci/issues/5898) for adding a name / label to builds.
